### PR TITLE
Fixed incorrectly connected Storyboards in Example project

### PR DESCRIPTION
**Pull request by askielboe**
This fixes a few issues in the example project which prevented testing device motion and magnetometer updates, by referencing wrong classes and methods.

### CODE REVIEW

**Comment by freak4pc** [comment]
@askielboe This actually seems like a dupe of #13 , Which oddly wasn't merged

**Comment by askielboe** [comment]
hah, yea sorry I just realized that.. I should check the pull requests next time. :)

**Comment by freak4pc** [comment]
Actually thought this PR seems more concise so that would perhaps be a better choice :)
Would you mind amending your commit to have a more informative commit message and re-push it? 

something like a 

```
git commit --amend -m "Fixed incorrectly connected Storyboards in Example project"
git push -fu origin # You'll need the force push because you're amending your commit
```

**Comment by askielboe** [comment]
Yep, done!

**Pull request merged**
