### PR TITLE
Swift 4 and RxSwift 4.0

### PR DESCRIPTION
**Pull request by kustra**
Fixed the deprecation warnings after version bump.
Please publish new pod (1.3.0) after merging the PR.

### CODE REVIEW

**Comment by carlosypunto** [comment]
@freak4pc If it's perfect for you is perfect for me. Thanks. I had it pending for the weekend :-)

**Comment by freak4pc** [comment]
@carlosypunto Already merged and had a release out in GitHub (Carthage), just need you to push the Podspec up to Cocoapods when you have a chance :)

**Comment by carlosypunto** [comment]
As I see that everything goes very fast I will do it now with breakfast :-)

**Comment by carlosypunto** [comment]
@freak4pc it's published

**Comment by freak4pc** [comment]
👏 great job all, thanks @kustra and good luck on your first contribution!

**Comment by kustra** [comment]
Thanks for the fast response guys. Appreciate it. Great job!

**Pull request merged**
